# cython: language_level=3
from src.routes.dashboard import dashboard_bp
from src.routes.settings import settings_bp
from src.routes.speedtest import speedtest_bp
from src.routes.process_info import process_bp
from src.routes.auth import auth_bp
from src.routes.other import other_bp
from src.routes.smtp_email_config import smtp_email_config_bp
from src.routes.user_management import user_management_bp
from src.routes.historical_system_metrics import graphs_bp
from src.routes.firewall import firewall_bp
from src.routes.health import health_bp
from src.routes.api import api_bp
from src.routes.ec2_metadata import ec2_metadata_bp
from src.routes.error_handlers import error_handlers_bp
from src.routes.profile import profile_bp
from src.routes.prometheus import prometheus_bp
from src.routes.alert_route import alert_bp
from src.routes.update_webhooks import webhooks_bp
from src.routes.activation import activation_bp
from src.routes.services import services_bp
from src.routes.api_metrics import metrics_bp
from src.routes.middleware import middleware_bp
from src.routes.cmd_route import cmd_bp
from src.routes.discussion_board import discussion_board_bp
from src.routes.unified_logger import unified_logger_bp