# ==========================
# Application Metadata
# ==========================
[app.meta]
NAME = SystemGuard
VERSION = 1.0.2
DESCRIPTION = A web application to monitor and manage system resources.
AUTHOR = SystemGuard Team
YEAR = 2025
CONTACT_EMAIL = ""
PRE_RELEASE = True

# ==========================
# Application Settings
# ==========================
[app.settings]
UNDER_MAINTENANCE = False


# ==========================
# Database Configuration
# ==========================
[database]
POOL_SIZE = 10
MAX_OVERFLOW = 5

# ==========================
# Session Configuration
# ==========================
[session]
COOKIE_HTTPONLY = True
COOKIE_SAMESITE = Lax
COOKIE_SECURE = False

# ==========================
# Prometheus Integration
# ==========================
[monitoring.prometheus]
BASE_URL = http://localhost:9090
QUERY_API = http://localhost:9090/api/v1/query_range
TARGETS_API = http://localhost:9090/api/v1/targets
RELOAD_URL = http://localhost:9090/-/reload

[monitoring.alertmanager]
BASE_URL = http://localhost:9093


# ==========================
# Logging
# ==========================
[logging]
LEVEL = INFO

# ==========================
# System Metrics Service
# ==========================
[metrics.settings]
BYTES_PER_GB = 1073741824
BYTES_PER_MB = 1048576
BYTES_PER_KB = 1024
UPDATE_INTERVAL = 1.0
CACHE_EXPIRATION = 3600
DIVIDE_BY_1024 = False

# ==========================
# Testing webserver
# ==========================
[webserver.test]
HOST = 0.0.0.0
PORT = 5001
DEBUG = True

# ==========================
# Production webserver
# ==========================
[webserver.production]
HOST = 0.0.0.0
PORT = 5050
DEBUG = False

# ==========================
# AWS Metadata Service
# ==========================
[aws.metadata]
METADATA_URL = http://169.254.169.254/latest/meta-data/
TOKEN_TTL_SECONDS = 21600
TOKEN_URL = http://169.254.169.254/latest/api/token

# ==========================
# AWS S3 Configuration Data Retention( not yet implemented )
# ==========================
; [aws.s3]
; BUCKET_NAME = systemguard-backups
; REGION = us-east-1
; ENDPOINT_URL = https://s3.amazonaws.com
; USE_SSL = True

