groups:
- name: SystemGuard's alert rules
  rules:
  - alert: avg by (instance) (cpu_temperature) > 90
    annotations:
      description: avg by (instance) (cpu_temperature) > 90
      runbook_url: avg by (instance) (cpu_temperature) > 90
      summary: avg by (instance) (cpu_temperature) > 90`
    expr: avg by (instance) (cpu_temperature) > 90
    for: 5m
    labels:
      severity: info
